apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-app-service
  namespace: argocd  
  labels:
    app: prometheus-node-app    
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
      nodePort: 32000 

  selector:
    app: prometheus-node-app

