apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  namespace: argocd
  name: node-app-monitor
  labels:
    release: kube-prom-stack  # Match this label to your Prometheus release!
spec:
  selector:
    matchLabels:
      app: prometheus-node-app
  namespaceSelector:
    matchNames:
    - default  
  endpoints:
  - path: /metrics
    port: "http"
    interval: 15s

